### PR TITLE
fix: Truncate masterclass card description

### PR DESCRIPTION
**Pull request by aaryanporwal**
# Done
- Truncate masterclass card's description.
- Update dummy import data to include long description and a valid video, for demo purposes.

Fixes: [WD-14581](https://warthogs.atlassian.net/browse/WD-15481?atlOrigin=eyJpIjoiMTQ3YmJjN2IwNjBkNGI5ZGEyYzI0MjFkMTQ2NWUwZjkiLCJwIjoiaiJ9)

[WD-14581]: https://warthogs.atlassian.net/browse/WD-14581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by finn-rm — APPROVED** [review]
lgtm!

**Comment by aaryanporwal** [comment]
> FYI this doesn't fix https://warthogs.atlassian.net/browse/WD-15481

Hey @Lukewh , yes we discussed this but the `see more` hyperlink didn't have enough space when I was using `u-truncate`. But now that we're using jinja `truncate` it looks good. Thanks for pointing it out. I've created a PR #62 to address this.

**Comment by Lukewh** [comment]
No, to clarify, you have linked the wrong issue - the linked issue is unrelated to masterclasses.

**Comment by aaryanporwal** [comment]
> No, to clarify, you have linked the wrong issue - the linked issue is unrelated to masterclasses.

Aha! I see I swapped WD-15481 with WD-14581, but the link was pointing correctly to 15481. Only the text had a typo. Fixed it nevertheless, also got a nice feature due to this. Win-win!

**Pull request merged**
